### Post new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Add a new one!",
    "author": "Mr Twitch",
    "url": "www.mrtwitch.com",
    "likes": 999
}

### Post new blog without likes
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "No likes!",
    "author": "Mr Twitch",
    "url": "www.mrtwitch.com"
}


### Update a blog

PUT http://localhost:3001/api/blogs/600c9559a22ae0678b15d0ba
Content-Type: application/json

{
    "likes": 10
}


### POST Create a new user
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "Jdog",
    "name": "Jimmy",
    "password": "pass1234"
}

