### Post new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "A BLOG",
    "author": "Mr Twitch",
    "url": "www.mrtwitch.com",
    "likes": 999
}

### Post new blog without likes
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "No likes!",
    "author": "Mr Twitch",
    "url": "www.mrtwitch.com"
}


### Update a blog

PUT http://localhost:3001/api/blogs/600c9559a22ae0678b15d0ba
Content-Type: application/json

{
    "likes": 10
}


### POST Create a new user
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    	
			"username": "daveDingo",
            "name": "dave2222",
			"password": "pass123"
	
}


### POST Create a new user with missing username
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    
    "name": "Mr Thomas",
    "password": "pass1234"
}

###POST login with correct details.
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    	
			"username": "daveDingo",
			"password": "pass123"
	
}

###POST login with incorrect password.
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    	
			"username": "daveDingo",
			"password": "wrongPassword"
	
}


###POST login with incorrect username.

POST http://localhost:3001/api/login/
Content-Type: application/json

{
    	
			"username": "incorrectUsername",
			"password": "wrongPassword"
	
}


